# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iplookup < Formula
  desc "Fast and simple command-line IP address lookup tool"
  homepage "https://github.com/gofika/iplookup"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gofika/iplookup/releases/download/v0.2.8/iplookup_0.2.8_darwin_x86_64.tar.gz"
      sha256 "b93e893d5d85f281d5d54ef30f91993ae8fef6662d9bc383e3ed94bc00b493cd"

      define_method(:install) do
        bin.install "iplookup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gofika/iplookup/releases/download/v0.2.8/iplookup_0.2.8_darwin_arm64.tar.gz"
      sha256 "01af950098bb9ccce0783cc961edee3096fbc3e1730875d32d190519e43f05ad"

      define_method(:install) do
        bin.install "iplookup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gofika/iplookup/releases/download/v0.2.8/iplookup_0.2.8_linux_x86_64.tar.gz"
      sha256 "a4425434053c0341d149b7e164595e4194daf90027823d08c6d0e3ae3ebe3d0b"
      define_method(:install) do
        bin.install "iplookup"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gofika/iplookup/releases/download/v0.2.8/iplookup_0.2.8_linux_armv6.tar.gz"
      sha256 "a14ef74c9244e3f66c013e945d1ce5d7e1d298e13516582c576f32d01201b38a"
      define_method(:install) do
        bin.install "iplookup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gofika/iplookup/releases/download/v0.2.8/iplookup_0.2.8_linux_arm64.tar.gz"
      sha256 "1ff4e4c1111214671627d460290dfe5acf1e3b9b7c277da41768fbab2d155c04"
      define_method(:install) do
        bin.install "iplookup"
      end
    end
  end
end
