# This file was generated by GoReleaser. DO NOT EDIT.
cask "iplookup" do
  desc "Fast and simple command-line IP address lookup tool"
  homepage "https://github.com/gofika/iplookup"
  version "0.2.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iplookup"

  on_macos do
    on_intel do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.6/iplookup_0.2.6_darwin_x86_64.tar.gz"
      sha256 "991eeb09f255a9cd1334d6fd13dc7cd60bd25076c192f36ffd383db309c8d819"
    end
    on_arm do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.6/iplookup_0.2.6_darwin_arm64.tar.gz"
      sha256 "8d785675582c12d5482ccbe014adc3a41556264c7455750d1f4b3bcc09e0eb3a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.6/iplookup_0.2.6_linux_x86_64.tar.gz"
      sha256 "bca35022f08cbfa74a3c5edabbd8924c246975cd3122417fd039d7b126e4608b"
    end
    on_arm do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.6/iplookup_0.2.6_linux_arm64.tar.gz"
      sha256 "50eb8294dfefff782e4b81ecbd158132210cb9fe6ad19f4b698976c9d78029b0"
    end
  end

  # No zap stanza required
end
