# This file was generated by GoReleaser. DO NOT EDIT.
cask "iplookup" do
  desc "Fast and simple command-line IP address lookup tool"
  homepage "https://github.com/gofika/iplookup"
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iplookup"

  on_macos do
    on_intel do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.4/iplookup_0.2.4_darwin_x86_64.tar.gz"
      sha256 "7eeb12756a7309eb9d8ab27d0271c77b1ee216ba843c6c455dd0bab50fedabf5"
    end
    on_arm do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.4/iplookup_0.2.4_darwin_arm64.tar.gz"
      sha256 "64a4d3c66eda315a96dc66b6f88eba6b26afc74803ab4cba608d5de222efb79f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.4/iplookup_0.2.4_linux_x86_64.tar.gz"
      sha256 "267e1fe943b247409697c26ee0783eb6bcb7b90ee75c74bdb6f108614795cb6c"
    end
    on_arm do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.4/iplookup_0.2.4_linux_arm64.tar.gz"
      sha256 "417fcc150d72dddd4600b2e5c0310b15897d662e4c6cba91d7a8a93c92662bf1"
    end
  end

  # No zap stanza required
end
