# This file was generated by GoReleaser. DO NOT EDIT.
cask "iplookup" do
  desc "Fast and simple command-line IP address lookup tool"
  homepage "https://github.com/gofika/iplookup"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iplookup"

  on_macos do
    on_intel do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.2/iplookup_0.2.2_darwin_x86_64.tar.gz"
      sha256 "36d319ce81241e0de99aba1e466557e45ee04b580e9f9fa106c936d690c8fbc6"
    end
    on_arm do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.2/iplookup_0.2.2_darwin_arm64.tar.gz"
      sha256 "96d3853370e15997152bc3a0f8b442fdefb5b05e84c349998a5f03406825a395"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.2/iplookup_0.2.2_linux_x86_64.tar.gz"
      sha256 "35c58fac643096df737989c4cc0920ad8571c397a9c6693e9cd1c70504acc785"
    end
    on_arm do
      url "https://github.com/gofika/iplookup/releases/download/v0.2.2/iplookup_0.2.2_linux_arm64.tar.gz"
      sha256 "47b70c45d3e77fbc30e51e6f4951669365d7c6837e53b9893d011a5fc3eccd40"
    end
  end

  # No zap stanza required
end
