# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iplookup < Formula
  desc "Fast and simple command-line IP address lookup tool"
  homepage "https://github.com/gofika/iplookup"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gofika/iplookup/releases/download/v0.2.1/iplookup_0.2.1_darwin_x86_64.tar.gz"
      sha256 "9c89919832195151779f44dabc1ecf864e3f54a61dc7a6e2830119c22b54d421"

      def install
        bin.install "iplookup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gofika/iplookup/releases/download/v0.2.1/iplookup_0.2.1_darwin_arm64.tar.gz"
      sha256 "07010bdcc0eaa010c49c7f8dae70358f20ef6e27e373ff9285f83b0fd822cd3d"

      def install
        bin.install "iplookup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gofika/iplookup/releases/download/v0.2.1/iplookup_0.2.1_linux_x86_64.tar.gz"
      sha256 "b159ce7cd181a0e84f7a20a8a7268a7986fc2c7c6f876f4aba7bfdd910008609"
      def install
        bin.install "iplookup"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/gofika/iplookup/releases/download/v0.2.1/iplookup_0.2.1_linux_armv6.tar.gz"
      sha256 "44a7abb0b0d04136bd06b1a2cf166df2aba654d49e54388229833baa1f7934a2"
      def install
        bin.install "iplookup"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gofika/iplookup/releases/download/v0.2.1/iplookup_0.2.1_linux_arm64.tar.gz"
      sha256 "cb6e1c555c2d6fb36f10a5b03322372d58fd9bffd3fd23dc10404f5fa7f0d9ea"
      def install
        bin.install "iplookup"
      end
    end
  end

  test do
    system "#{bin}/iplookup", "-h"
  end
end
